[server]
headless = true

[theme]
primaryColor="#FF69B4"  # Bright pink for primary highlights
backgroundColor="#1E1E2F"  # Dark background
secondaryBackgroundColor="#2B2B3D"  # Sidebar background
textColor="#FFFFFF"  # White for main text
font="Courier New"  # Techno-vibe font

[sidebar]
mainPageName = "Home"